# Generated by Django 5.0 on 2024-01-24 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='book_author_table',
        ),
        migrations.AlterModelTable(
            name='bookauthor',
            table='author_table',
        ),
        migrations.AlterModelTable(
            name='bookreview',
            table='review_table',
        ),
        migrations.AlterModelTable(
            name='books',
            table='books_table',
        ),
    ]
