# Generated by Django 5.0 on 2024-01-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_table_alter_bookauthor_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image_book',
            field=models.ImageField(default='books_image/default_book_image.png', upload_to='media/books_image'),
        ),
    ]
